config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [] do
    collection do
      get :register
      get :login
      post :user_login
      post :user_register
      get  :logout
    end
  end
  root 'users#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create

  end

  def user_register
    @already = User.find_by_email(params[:user][:email])
    @user = User.new(new_params)
    if @already.blank?
      if @user.save
        sign_in :user, @user
        redirect_to welcomes_url
      else
        puts"sssssssssssssssssssssssssss here 1",@user.errors.messages.inspect
        flash[:success] = 'User Already Exist'
        render :register
      end
    else
      puts"sssssssssssssssssssssssssss here 1"
      flash[:success] = 'User Already Exist.'
      render :register
    end
  end

  def user_login
    @user  = User.find_by_email(params[:user][:email])
    if !@user.blank?
      if @user.valid_password?(params[:user][:password])
        sign_in :user, @user
        redirect_to  welcomes_url
      else
        flash[:error] = 'Invalid Email.'
        render :login
      end
    else
      flash[:error] = 'Invalid Credentials.'
      render :login
    end
  end

  def register
    @user = User.new
  end

  def logout
    sign_out current_user  if current_user
    redirect_to root_url
  end

  private

  def new_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RTH</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/login.html.erb
<main role="main">
  <div class="outer-wrapper d-flex align-items-center">
    <div class="wrap"  style="margin-top: 90px; margin-bottom: 20px">
      <div class="login-box">
        <div class="left text-center">
          <a href="" class="lg-logo">LOGO</a>

          <p class="mb-0">Don't have an account?</p>
          <p>Register an account now!</p>
          <a href="<%= register_users_url %>" class="btn btn-register">Register</a>
        </div>

        <div class="right text-center">
          <h2>Sign In </h2>
          <%= form_for :user, url: user_login_users_url, :html => {:id => "signinForm"} do |f|  %>
            <div class="md-form">
              <%= f.email_field :email , :class=>"form-control" , :id => "email"%>
              <label for="email">Email</label>
            </div>

            <div class="md-form">
              <%= f.password_field :password , :class=>"form-control" , :id => "password"%>
              <label for="password">Password</label>
            </div>
            <a href="" class="d-block text-right text-white">Forgot password?</a>
            <button type="submit" class="btn btn-register">Sign in</button>
          <% end %>

          <div class="social-head">
            <p class="para">Or Sign In with </p>
          </div>
          <div class="social-sign d-flex justify-content-center">
            <div class="fb">
              <a href=""><i class="fab fa-facebook-f"></i></a>
            </div>
            <div class="google">
              <a href=""><i class="fab fa-google"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/register.html.erb
<div class="outer-wrapper d-flex align-items-center" style="height: 100%">
  <div class="wrap" style="margin-top: 90px; margin-bottom: 20px">
    <div class="login-box">

      <div class="left text-center">
        <a class="lg-logo">
          LOGO
        </a>

        <p class="mb-0">Already have an account?</p>
        <p>Sign in to your account</p>
        <a href="<%= login_users_url %>" class="btn btn-register">Sign In</a>
      </div>
      <div class="right text-center">
        <h2>Sign Up </h2>
        <%= form_for @user , url: user_register_users_url, :html => {:id => "signupForm"} do |f|  %>
          <div class="md-form">
            <%= f.text_field :first_name , :class=>"form-control" , :id => "firstname"%>
            <label for="firstname">First Name</label>
          </div>
          <div class="md-form">
            <%= f.text_field :last_name , :class=>"form-control" , :id => "lastname"%>
            <label for="lastname">Last Name</label>
          </div>

          <div class="md-form">
            <%= f.email_field :email , :class=>"form-control" , :id => "email"%>
            <label for="email">Email</label>
          </div>

          <div class="md-form">
            <%= f.password_field :password , :class=>"form-control" , :id => "password"%>
            <label for="password">Password</label>
          </div>
          <button type="submit" class="btn btn-register">Register</button>
        <% end %>
      </div>
    </div>
  </div>
</div>
</main>